### ISSUE TITLE
Update nicht möglich

### ISSUE THREAD

**Issue by maxkes** [Pleb-Team/pleb#20]
Update nicht möglich. Ich hab beide .apks probiert, et hat den Update-Prozess angefangen und dann abgebrochen. App deinstallieren und neu installieren hat dann funktioniert.
![2020-04-09 19 11 25](https://user-images.githubusercontent.com/8328446/78923188-1ab66480-7a98-11ea-9384-ff27d627a435.png)

**Comment by tschuldigung** [comment]
Solved in according branch. PR will follow
