### ISSUE TITLE
Musik Autoplay ausschalten

### ISSUE THREAD

**Issue by maxkes** [Pleb-Team/pleb#21]
Neeeeervt :-)

**Comment by tschuldigung** [comment]
Kompromiss: Musik bleibt, kann gerne gegen was besseres ausgetauscht werden, aber der On/Off Knopf sollte auf oberster Ebene direkt sichtbar sein (derzeit versteckt hier "..."

**Comment by tschuldigung** [comment]
Erleidgt. Außerdem bleibt die Musik aus, sobald einmal ausgeschaltet (nur wenn man eine neue Version des Spiels installiert bzw. einen neuen Build, wird es ggfs. wieder aktiviert). Der Musik-Knopf ist nun zugänglich auf oberster Ebene
